object UI {
    private const val appCompatVersion = "1.3.1"
    private const val activityVersion = "1.3.1"
    private const val fragmentVersion = "1.3.6"
    private const val constraintLayoutVersion = "2.1.0"
    private const val materialVersion = "1.4.0"
    private const val legacySupportVersion = "1.0.0"
    private const val recyclerViewVersion = "1.2.1"
    const val navigationVersion = "2.3.1"
//    const val navigationVersion = "2.5.3"
    private const val datastorePrefVersion = "1.0.0"

    const val appCompat = "androidx.appcompat:appcompat:$appCompatVersion"
    const val activity = "androidx.activity:activity-ktx:$activityVersion"
    const val fragment = "androidx.fragment:fragment-ktx:$fragmentVersion"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"
    const val material = "com.google.android.material:material:$materialVersion"
    const val legacySupport = "androidx.legacy:legacy-support-v4:$legacySupportVersion"
    const val recyclerView = "androidx.recyclerview:recyclerview:$recyclerViewVersion"
    const val datastorePref = "androidx.datastore:datastore-preferences:$datastorePrefVersion"
    const val navigationRuntime ="androidx.navigation:navigation-runtime-ktx:$navigationVersion"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:$navigationVersion"
    const val navigationUI = "androidx.navigation:navigation-ui-ktx:$navigationVersion"
}